wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 1
      4: 3.7.9
      5: 0.10.33
      8:
      - 1
      - 3
      - 5
early_stopping:
  desc: null
  value: 10
epochs:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.001
